#!/bin/bash -l
# Second part of smoke run launching - this part is generated by script and has run date in it

WRFRUNDIR=/center1/d/UAFSMOKE/src/WRFV351/test/em_real
module load slurm

cd $WRFRUNDIR
echo "`date`: In $WRFRUNDIR"
rm wrfbdy_d01
rm wrfchemi_d01
rm wrfchemi_gocart_bg_d01
rm wrffirechemi_d01
rm wrfinput_d01
rm wrf_chem_input_d01
rm met_em.d*
rm rsl.*
ln -sf /center1/d/UAFSMOKE/src/PREP-CHEM-SRC-1.4_chinook/bin/wrf_chemi_input-T-{fromdate:s}-000000-g1-gocartBG.bin wrf_gocart_backg
ln -sf /center1/d/UAFSMOKE/src/PREP-CHEM-SRC-1.4_chinook/bin/wrf_chemi_input-T-{fromdate:s}-000000-g1-bb.bin emissfire_d01
ln -sf /center1/d/UAFSMOKE/src/PREP-CHEM-SRC-1.4_chinook/bin/wrf_chemi_input-T-{fromdate:s}-000000-g1-ab.bin emissopt3_d01
ln -sf /center1/d/UAFSMOKE/src/WPS351/met_em.d* .
ln -sf /center1/d/UAFSMOKE/run/wrfout/2017_singles/wrfout_d01_{fromdate:s}_00:00:00 wrf_chem_input_d01

echo "`date`: Submitting job."
sbatch {slurmscript:s}
