#!/bin/bash
# Second part of smoke run launching - this part is generated by script and has run date in it

WRFRUNDIR=/center/d/UAFSMOKE/src/WRFV351/test/em_real

cd $WRFRUNDIR
echo "`date`: In $WRFRUNDIR"
rm wrfbdy_d01
rm wrfchemi_d01
rm wrfchemi_gocart_bg_d01
rm wrffirechemi_d01
rm wrfinput_d01
rm met_em.d*
rm rsl.*
ln -sf /center/d/UAFSMOKE/src/PREP-CHEM-SRC-1.4/bin/wrf_chemi_input-T-{fromdate:s}-000000-g1-gocartBG.bin wrf_gocart_backg
ln -sf /center/d/UAFSMOKE/src/PREP-CHEM-SRC-1.4/bin/wrf_chemi_input-T-{fromdate:s}-000000-g1-bb.bin emissfire_d01
ln -sf /center/d/UAFSMOKE/src/PREP-CHEM-SRC-1.4/bin/wrf_chemi_input-T-{fromdate:s}-000000-g1-ab.bin emissopt3_d01
ln -s /center/d/UAFSMOKE/src/WPS351/met_em.d* .

echo "`date`: Submitting job."
qsub {torquescript:s}
